name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: actions/upload-artifact@v7
      with:
        name: src
        path: src

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/download-artifact@v8
      with:
        name: src
        path: src
    - name: Setup ssh keys
      run: |
        mkdir ~/.ssh
        echo '${{ secrets.SSH_PRIVATE_KEY }}' > ~/.ssh/id_rsa
        echo '${{ secrets.SSH_PUBLIC_KEY }}' > ~/.ssh/id_rsa.pub
        chmod 400 ~/.ssh/id_rsa
    - name: Deploy to librechurch.org
      run: rsync -e "ssh -o StrictHostKeyChecking=no" -arvc src/ lki01-librechurchweb@lki01.hostsharing.net:/home/pacs/lki01/users/librechurchweb/doms/librechurch.org/htdocs-ssl