name: deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup ssh keys
      run: |
        mkdir ~/.ssh
        echo '${{ secrets.SSH_PRIVATE_KEY }}' > ~/.ssh/id_rsa
        echo '${{ secrets.SSH_PUBLIC_KEY }}' > ~/.ssh/id_rsa.pub
        chmod 400 ~/.ssh/id_rsa
    - name: Deploy to librechurch.org
      run: rsync -e "ssh -o StrictHostKeyChecking=no" -arvc --delete -i src/ lki01-librechurchweb@lki01.hostsharing.net:/home/pacs/lki01/users/librechurchweb/doms/librechurch.org/htdocs-ssl