name: deploy-preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions: write-all

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./src/
          wait-for-pages-deployment: true
